spring:
  profiles: dev

  datasource:
    master:
      url: jdbc:mysql://192.168.1.30/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
      username: root
      password: shihuai1993A
    cluster:
      url: jdbc:mysql://192.168.1.30/slave?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false
      username: root
      password: shihuai1993A


